services:
  db:
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: portfolio
    volumes:
      - ./scripts/init-dbs.sql:/docker-entrypoint-initdb.d/init-dbs.sql
    healthcheck:
      disable: true
