import {
  SiWebassembly,
  SiRust,
  SiPython,
  SiSpotify,
  SiTypescript,
  SiReact,
  SiCss3,
  SiTailwindcss,
  SiExpress,
  SiHtml5,
  SiKubernetes,
  SiJenkins,
  SiGo,
  SiHelm,
  SiDocker,
  SiNodedotjs,
  SiPostgresql,
  SiJavascript,
  SiWordpress,
  SiSvelte,
} from "react-icons/si";
import { LiaJava } from "react-icons/lia";

const TECH_ICONS = {
  webassembly: SiWebassembly,
  rust: SiRust,
  python: SiPython,
  "spotify api": SiSpotify,
  typescript: SiTypescript,
  javascript: SiJavascript,
  react: SiReact,
  css: SiCss3,
  tailwindcss: SiTailwindcss,
  "express.js": SiExpress,
  html: SiHtml5,
  kubernetes: SiKubernetes,
  jenkins: SiJenkins,
  go: SiGo,
  helm: SiHelm,
  docker: SiDocker,
  node: SiNodedotjs,
  postgresql: SiPostgresql,
  java: LiaJava,
  wordpress: SiWordpress,
  svelte: SiSvelte,
  "node.js": SiNodedotjs,
};

export default TECH_ICONS;
